"""Update user_id to string

Revision ID: 25904066c4b1
Revises: b8f4c8ed96c4
Create Date: 2023-08-11 12:40:54.816505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25904066c4b1'
down_revision = 'b8f4c8ed96c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
