"""empty message

Revision ID: ea7694de0d16
Revises: 938c59c75361
Create Date: 2023-09-12 11:03:11.584805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7694de0d16'
down_revision = '938c59c75361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('savings', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('wants', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('wants')
        batch_op.drop_column('savings')
        batch_op.drop_column('needs')

    # ### end Alembic commands ###
