"""Added total_expenses and surplus_deficit to database

Revision ID: 938c59c75361
Revises: 25904066c4b1
Create Date: 2023-08-18 11:00:10.798152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938c59c75361'
down_revision = '25904066c4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_expenses', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('surplus_deficit', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('surplus_deficit')
        batch_op.drop_column('total_expenses')

    # ### end Alembic commands ###
