"""Add income and user_token columns to expenses

Revision ID: b8f4c8ed96c4
Revises: 
Create Date: 2023-07-26 14:42:28.449996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f4c8ed96c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_token')
        batch_op.drop_column('income')

    # ### end Alembic commands ###
